### ISSUE TITLE
It's no longer on Nexus Mods?

### ISSUE THREAD

**Issue by Zireael07** [TheMarkie/VanillaMatters#2]
Title. The page says deleted.

**Comment by TheMarkie** [comment]
Yep, I've removed the page from Nexus Mods, the ModDB page is also pending removal. There are a few reasons but it's mainly that the update has tripled in scope. I feel maintaining two mod pages plus a repo page is too much. When the next beta finishes, I'll aim for my own website or at least a github io.

Right now THIS is the ONLY place you can get in on the latest beta. I like the idea of an open repo which is more user friendly and safe.

**Comment by Zireael07** [comment]
The README should be updated then ;)

**Comment by TheMarkie** [comment]
README updated.
